version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
  #  restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.99.100';registry_external_url 'http://192.168.99.100:5005'
        # Add any other gitlab.rb configuration here, each on its own line
      GITLAB_ROOT_PASSWORD: "root_git"
      GITLAB_TIMEZONE: "Asia/Seoul"  
    ports:
      - '80:80'
      - '5005:5005'
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'    
  jenkins:
    #image: 'jenkins:latest'
    image: 'moricom/jenkins:latest'
    user: root
    ports:
      - '8080:8080'
    volumes:
      - '/data/jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/usr/bin/docker'
  sonarqube:
    image: 'sonarqube:latest'
    ports:
      - '9000:9000'
    volumes:
      - '/data/sonarqube/conf:/opt/sonarqube/conf'
      - '/data/sonarqube/data:/opt/sonarqube/data'
      - '/data/sonarqube/logs:/opt/sonarqube/logs'
      - '/data/sonarqube/extensions:/opt/sonarqube/extensions'
  registry:
    image: 'registry:2.0'
    ports:
      - '5000:5000'
