version: '3'
services:
  eclipse-che:
    image: 'eclipse/che:6.19.0'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/data/eclipse:/data'
    command:
      - start
    environment:
      CHE_PORT: '8082'
      CHE_MULTIUSER: 'true'
      CHE_IP: '192.168.99.100'
      CHE_HOST: '192.168.99.100'
